amcl:
  #Overall filter parameters
  min_particles: 500
  max_particles: 2000
  kld_err: 0.05
  kld_z: 0.99
  update_min_d: 0.25
  update_min_a: 0.2
  resample_interval: 1
  transform_tolerance: 0.1
  recovery_alpha_slow: 0.1
  recovery_alpha_fast: 0.2
  initial_pose_x: 0.0
  initial_pose_y: 0.0
  initial_pose_a: 0.0
  initial_cov_xx: 0.25
  initial_cov_yy: 0.25
  initial_cov_aa: 0.685
  gui_publish_rate: 10.0
  save_pose_rate: 0.5
  use_map_topic: true
  first_map_only: false
  selective_resampling: false

  #Laser model parameters
  laser_min_range: 10.0
  laser_max_range: 20.0
  laser_max_beams: 100
  laser_z_hit: 0.95
  laser_z_short: 0.1
  laser_z_max: 0.05
  laser_z_rand: 0.5
  laser_sigma_hit: 0.2
  laser_lambda_short: 0.1
  laser_likelihood_max_dist: 2.0
  laser_model_type: likelihood_field

  #Odometry model parameters
  odom_model_type: diff
  odom_alpha1: 0.2
  odom_alpha2: 0.2
  odom_alpha3: 0.2
  odom_alpha4: 0.2
  odom_alpha5: 0.1
  odom_frame_id: odom
  base_frame_id: base_link
  global_frame_id: map
  tf_broadcast: true


