global_frame: odom
robot_base_frame: base_link
update_frequency: 5.0
static_map: false
rolling_window: true
track_unknown_space: true

weight: 100.0
height: 100.0

plugins:
  - { name: obstacles_laser,           type: "costmap_2d::ObstacleLayer" }
  - { name: inflation,                 type: "costmap_2d::InflationLayer" }